source 'https://rubygems.org'

gem 'sinatra', '~>1.3', require: 'sinatra/base'
gem 'activesupport', '~> 3.2', require: 'active_support/core_ext'
gem 'koala', '~> 1.6'
gem 'romkan', '~> 0.4'
gem 'romankana', '~> 0.1'

group :development do
	gem 'sinatra-contrib', '~>1.3', require: 'sinatra/reloader'
end
